### ISSUE TITLE
存在环境温度丢失情况

### ISSUE THREAD

**Issue by weiyideai520** [mypal/ha-dsair#17]
昨天配置好后可以看到 温度，
但是今天发现所有的机器都没有温度显示了。
<a href="https://imgtu.com/i/WoisfA"><img src="https://z3.ax1x.com/2021/07/28/WoisfA.png" alt="WoisfA.png" border="0" /></a>

**Comment by weiyideai520** [comment]
如果大金自己的温湿度无法完美获取的话，是否可以绑定其他温湿度计。
以实现current_temp的显示

**Comment by mypal** [comment]
你是B611网关？绑定其他温度计在开发中了

**Comment by weiyideai520** [comment]
是C611，我看到更新了，我正在绑定温湿度，辛苦了

**Comment by mypal** [comment]
#18 关联功能已支持
[v1.3.0](https://github.com/mypal/ha-dsair/releases/tag/1.3.0)版本已解决
