### ISSUE TITLE
dsair1.3.0 配置未成功-HA21.9.4 

### ISSUE THREAD

**Issue by linooy** [mypal/ha-dsair#24]
![QQ图片20210911225944](https://user-images.githubusercontent.com/35637928/132952125-8e404c75-670b-40dd-8401-d01910245848.png)
 如图所示，在这个阶段一直转圈，最后显示：未知的错误
附上DEBUG日志
[home-assistant.log](https://github.com/mypal/ha-dsair/files/7148065/home-assistant.log)

**Comment by mypal** [comment]
预计1.3.1修复

**Comment by mypal** [comment]
> 问一下 空气传感仪 BRY88AB151K 支持吗？

对传感器型号没限制，只要金制空气里面能显示的，理论上都可以支持
