### ISSUE TITLE
请问是否支持DTA117D611网关吗？

### ISSUE THREAD

**Issue by mickeyyeung** [mypal/ha-dsair#27]
请问是否支持DTA117D611网关吗？

**Comment by xrh0905** [comment]
用金制空气APP吗?是的话选C611试试

**Comment by xrh0905** [comment]
@mickeyyeung

**Comment by dx2727** [comment]
DTA117D611在瀚思论坛上有反馈可以识别机子和空气传感器，并无法操控T T，我接下去安装的也是D的网关，不知道大神有没有办法更新

**Comment by StevenHome93** [comment]
> 

我也是DTA117D611，配置界面的时候选择DTA117C611，成功控制开关，调温。内机4台，都可以单独控制。

**Comment by mypal** [comment]
> > 
> 
> 我也是DTA117D611，配置界面的时候选择DTA117C611，成功控制开关，调温。内机4台，都可以单独控制。

如果D和C协议相同的话，我回头更新下配置项，把D611加到选项里面
