### ISSUE TITLE
为什么这个不能添加两次呀

### ISSUE THREAD

**Issue by maao514** [mypal/ha-dsair#33]
我再添加一次里面提示只能在ha设置一个大金服务器，但是家里有两台服务器 有没有办法让两台都连接这个服务呀

**Comment by lynn901** [comment]
> 我再添加一次里面提示只能在ha设置一个大金服务器，但是家里有两台服务器 有没有办法让两台都连接这个服务呀
感觉复制一下插件，换个名字

**Comment by xrh0905** [comment]
#46 @maao514 
简单改了改 不一定有效 慎用
记得先备份再测试

**Comment by mypal** [comment]
> > 我再添加一次里面提示只能在ha设置一个大金服务器，但是家里有两台服务器 有没有办法让两台都连接这个服务呀
> 
> 感觉复制一下插件，换个名字

项目最初设计没考虑多网关情况，绝大部分用户应该都是一个网关，没想到有啥场景需要两个网关，是有多台外机么？支持多网关，改写成本有点高，也没有测试条件，考虑下这个方法迂回吧。
