### ISSUE TITLE
能支持DTA117D611吗？

### ISSUE THREAD

**Issue by walterhertz** [mypal/ha-dsair#34]
能支持DTA117D611吗？

**Comment by ypwub5** [comment]
我这里 D611 用 C611 的选项可以正常使用.

可以尝试把盒子拆开. 里面实际上是个 8266 做的 WiFi 转 RJ45, 可以直接把网线插到主板口上, 有线更稳定

**Comment by walterhertz** [comment]
谢谢

> 我这里 D611 用 C611 的选项可以正常使用.
> 
> 可以尝试把盒子拆开.里面实际上是个 8266 做的 WiFi 转 RJ45， 可以直接把网线插到主板口上， 有线更稳定

谢谢

**Comment by xrh0905** [comment]
修好了可以Close一下
