### ISSUE TITLE
又来热乎的报错了...

### ISSUE THREAD

**Issue by sephrioth** [mypal/ha-dsair#44]
插件已经是最新版(非release)，HA 是 2023.2.0

[homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for ds_air using this method at custom_components/ds_air/__init__.py, line 50: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by xrh0905** [comment]
看报错是提示要弃用旧方法了 暂时应该不影响
我去改一下试试

**Comment by xrh0905** [comment]
解决 #45

**Comment by sephrioth** [comment]
确认解决， 感谢高效的作者!

**Comment by xrh0905** [comment]
> 确认解决， 感谢高效的作者!

不用谢。以及我不是作者。
