### ISSUE TITLE
接入HA后使用正常，但是hass bridge到homekit后无法控制

### ISSUE THREAD

**Issue by Niven-F** [mypal/ha-dsair#54]
接入HA后，在HA使用正常，但是hass bridge到homekit，homekit内能看到设备，但无法控制。无法正常访问。

**Comment by xrh0905** [comment]
请详细描述一下问题 是完全不能控制吗 风速和温度都不行吗 有没有截图 日志中有没有报错 网关的型号 ha的版本和插件版本

**Comment by neverland1107** [comment]
已经解决了
